<a href="https://colab.research.google.com/github/MK545BH/IT7009-Project/blob/main/IT7009_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IT7009 Project
## Part 1: Data preprocessing.
### Importing libraries and Data:

In [2]:
# importing all neccasary libraries.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import VarianceThreshold
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
# Importing the uncleaned "Raw" dataset.
RAW_PATH = "Dataset_Brief_2.csv"   # upload this file to the Colab session storage first
df_raw = pd.read_csv(RAW_PATH, low_memory=False) # added the file path to a constant for ease of use.

print("Raw dataset shape:", df_raw.shape) 
df_raw.head()

Raw dataset shape: (48826, 47)

,flow_duration,Header_Length,Protocol Type,Duration,Rate,Srate,Drate,fin_flag_number,syn_flag_number,rst_flag_number,...,Std,Tot size,IAT,Number,Magnitue,Radius,Covariance,Variance,Weight,label
0,4.835233,1713517.54,16.89,66.33,634.919224,634.919224,0.0,0.0,0.0,0.0,...,23.51914405190254,540.23,8.375931e+07,9.5,32.983477,31.837886,3663.34722,0.14,141.55,Mirai-udpplain
1,0.000000,54.0,6.0,64.00,2.671835,2.671835,0.0,0.0,1.0,0.0,...,0.0,54.0,8.297303e+07,9.5,10.392305,0.000000,0.00000,0.0,141.55,DoS-SYN_Flood
2,0.000000,54.0,6.0,64.00,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,54.0,8.333120e+07,9.5,10.392305,0.000000,0.00000,0.0,141.55,DDoS-PSHACK_Flood
3,0.000000,0.0,1.0,64.00,160.127665,160.127665,0.0,0.0,0.0,0.0,...,0.0,42.0,8.312889e+07,9.5,9.165151,0.000000,0.00000,0.0,141.55,DDoS-ICMP_Flood
4,0.000000,54.0,6.0,64.00,1.262448,1.262448,0.0,1.0,0.0,1.0,...,0.0,54.0,8.334516e+07,9.5,10.392305,0.000000,0.00000,0.0,141.55,DDoS-RSTFINFlood

### Data Analysis

In [4]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 48826 entries, 0 to 48825
Data columns (total 47 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   flow_duration    48815 non-null  float64
 1   Header_Length    48815 non-null  str
 2   Protocol Type    48816 non-null  str
 3   Duration         48816 non-null  float64
 4   Rate             48814 non-null  float64
 5   Srate            48816 non-null  float64
 6   Drate            48811 non-null  float64
 7   fin_flag_number  48814 non-null  float64
 8   syn_flag_number  48816 non-null  float64
 9   rst_flag_number  48815 non-null  float64
 10  psh_flag_number  48815 non-null  str
 11  ack_flag_number  48814 non-null  float64
 12  ece_flag_number  48816 non-null  float64
 13  cwr_flag_number  48816 non-null  float64
 14  ack_count        48816 non-null  float64
 15  syn_count        48813 non-null  float64
 16  fin_count        48815 non-null  float64
 17  urg_count        48816 non-null  float64
 18  rst_count        48816 non-null  str
 19  HTTP             48814 non-null  float64
 20  HTTPS            48814 non-null  str
 21  DNS              48813 non-null  float64
 22  Telnet           48816 non-null  float64
 23  SMTP             48816 non-null  float64
 24  SSH              48814 non-null  float64
 25  IRC              48816 non-null  float64
 26  TCP              48813 non-null  float64
 27  UDP              48815 non-null  float64
 28  DHCP             48816 non-null  float64
 29  ARP              48813 non-null  float64
 30  ICMP             48814 non-null  str
 31  IPv              48814 non-null  str
 32  LLC              48816 non-null  str
 33  Tot sum          48815 non-null  float64
 34  Min              48814 non-null  str
 35  Max              48814 non-null  float64
 36  AVG              48812 non-null  float64
 37  Std              48815 non-null  str
 38  Tot size         48814 non-null  str
 39  IAT              48814 non-null  float64
 40  Number           48814 non-null  float64
 41  Magnitue         48815 non-null  float64
 42  Radius           48815 non-null  float64
 43  Covariance       48815 non-null  float64
 44  Variance         48816 non-null  str
 45  Weight           48814 non-null  float64
 46  label            48826 non-null  str
dtypes: float64(34), str(13)
memory usage: 17.5 MB

In [ ]:
# Provides a detailed description of the data.
df_raw.describe(include='all').T.head(20)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
flow_duration,48815.0,NaN,NaN,NaN,14.495303,382.599894,-999.0,0.0,0.0,0.128624,47629.094561
Header_Length,48815,15623,54.0,14557,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Protocol Type,48816,915,6.0,22721,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Duration,48816.0,NaN,NaN,NaN,66.276401,12.9069,0.0,64.0,64.0,64.0,255.0
Rate,48814.0,NaN,NaN,NaN,8664.10689,89626.647942,-999.0,2.095422,15.69341,128.325003,3145728.0
Srate,48816.0,NaN,NaN,NaN,8663.824629,89624.823444,-999.0,2.095305,15.69341,128.351765,3145728.0
Drate,48811.0,NaN,NaN,NaN,0.000001,0.000089,0.0,0.0,0.0,0.0,0.014636
fin_flag_number,48814.0,NaN,NaN,NaN,0.083583,0.276764,0.0,0.0,0.0,0.0,1.0
syn_flag_number,48816.0,NaN,NaN,NaN,0.204359,0.403237,0.0,0.0,0.0,0.0,1.0
rst_flag_number,48815.0,NaN,NaN,NaN,0.088559,0.284109,0.0,0.0,0.0,0.0,1.0
psh_flag_number,48815,3,0.0,44599,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ack_flag_number,48814.0,NaN,NaN,NaN,0.128918,0.335113,0.0,0.0,0.0,0.0,1.0
ece_flag_number,48816.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cwr_flag_number,48816.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ack_count,48816.0,NaN,NaN,NaN,0.090967,0.285128,0.0,0.0,0.0,0.0,2.7
syn_count,48813.0,NaN,NaN,NaN,0.340677,0.67151,0.0,0.0,0.0,0.14,5.76
fin_count,48815.0,NaN,NaN,NaN,0.101252,0.304938,0.0,0.0,0.0,0.0,5.28
urg_count,48816.0,NaN,NaN,NaN,6.259235,80.044761,0.0,0.0,0.0,0.0,2999.0
rst_count,48816,2334,0.0,35224,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HTTP,48814.0,NaN,NaN,NaN,0.053714,0.225455,0.0,0.0,0.0,0.0,1.0

### Data inspection:

In [ ]:
feature_cols = [c for c in df_raw.columns if c != 'label'] #Separates input variables (features) from the target variable (Label)
print("Number of feature columns:", len(feature_cols))
suspect = [c for c in df_raw.columns if any(k in c.lower() for k in ['id', 'date', 'time', 'timestamp']) #Identifies potential identifiers or time-based metadata
           and c != 'flow_duration']
print("Identifier/date-like column names found:", suspect if suspect else "None")
print("Target classes:", df_raw['label'].nunique(), "| Missing labels:", df_raw['label'].isnull().sum()) #Verifies target integrity.